[2022-10-05T09:27:25.672+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dump_to_s3.collect_messages manual__2022-10-05T09:27:21.016272+00:00 [queued]>
[2022-10-05T09:27:25.678+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dump_to_s3.collect_messages manual__2022-10-05T09:27:21.016272+00:00 [queued]>
[2022-10-05T09:27:25.678+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-10-05T09:27:25.678+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-10-05T09:27:25.678+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-10-05T09:27:25.744+0000] {taskinstance.py:1383} INFO - Executing <Task(_PythonDecoratedOperator): collect_messages> on 2022-10-05 09:27:21.016272+00:00
[2022-10-05T09:27:25.746+0000] {standard_task_runner.py:54} INFO - Started process 10799 to run task
[2022-10-05T09:27:25.750+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'dump_to_s3', 'collect_messages', 'manual__2022-10-05T09:27:21.016272+00:00', '--job-id', '46', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmp4v_l1qc7']
[2022-10-05T09:27:25.751+0000] {standard_task_runner.py:83} INFO - Job 46: Subtask collect_messages
[2022-10-05T09:27:25.752+0000] {dagbag.py:525} INFO - Filling up the DagBag from /workspaces/pipeline-environment/test_airflow/dags/pipeline.py
[2022-10-05T09:27:25.837+0000] {logging_mixin.py:117} WARNING - /usr/local/lib/python3.10/site-packages/airflow/models/dag.py:3393 RemovedInAirflow3Warning: Param `schedule_interval` is deprecated and will be removed in a future release. Please use `schedule` instead.
[2022-10-05T09:27:25.838+0000] {taskmixin.py:205} WARNING - Dependency <Task(_PythonDecoratedOperator): create_dump_file>, collect_messages already registered for DAG: dump_to_s3
[2022-10-05T09:27:25.839+0000] {taskmixin.py:205} WARNING - Dependency <Task(_PythonDecoratedOperator): collect_messages>, create_dump_file already registered for DAG: dump_to_s3
[2022-10-05T09:27:25.839+0000] {taskmixin.py:205} WARNING - Dependency <Task(_PythonDecoratedOperator): create_dump_file>, collect_messages already registered for DAG: dump_to_s3
[2022-10-05T09:27:25.839+0000] {taskmixin.py:205} WARNING - Dependency <Task(_PythonDecoratedOperator): collect_messages>, create_dump_file already registered for DAG: dump_to_s3
[2022-10-05T09:27:25.839+0000] {taskmixin.py:205} WARNING - Dependency <Task(_PythonDecoratedOperator): create_dump_file>, collect_messages already registered for DAG: dump_to_s3
[2022-10-05T09:27:25.839+0000] {taskmixin.py:205} WARNING - Dependency <Task(_PythonDecoratedOperator): collect_messages>, create_dump_file already registered for DAG: dump_to_s3
[2022-10-05T09:27:25.839+0000] {taskmixin.py:205} WARNING - Dependency <Task(_PythonDecoratedOperator): create_dump_file>, collect_messages already registered for DAG: dump_to_s3
[2022-10-05T09:27:25.839+0000] {taskmixin.py:205} WARNING - Dependency <Task(_PythonDecoratedOperator): collect_messages>, create_dump_file already registered for DAG: dump_to_s3
[2022-10-05T09:27:25.839+0000] {taskmixin.py:205} WARNING - Dependency <Task(_PythonDecoratedOperator): create_dump_file>, collect_messages already registered for DAG: dump_to_s3
[2022-10-05T09:27:25.840+0000] {taskmixin.py:205} WARNING - Dependency <Task(_PythonDecoratedOperator): collect_messages>, create_dump_file already registered for DAG: dump_to_s3
[2022-10-05T09:27:25.840+0000] {taskmixin.py:205} WARNING - Dependency <Task(_PythonDecoratedOperator): create_dump_file>, collect_messages already registered for DAG: dump_to_s3
[2022-10-05T09:27:25.840+0000] {taskmixin.py:205} WARNING - Dependency <Task(_PythonDecoratedOperator): collect_messages>, create_dump_file already registered for DAG: dump_to_s3
[2022-10-05T09:27:25.840+0000] {taskmixin.py:205} WARNING - Dependency <Task(_PythonDecoratedOperator): collect_messages>, dump_to_s3 already registered for DAG: dump_to_s3
[2022-10-05T09:27:25.840+0000] {taskmixin.py:205} WARNING - Dependency <Task(_PythonDecoratedOperator): dump_to_s3>, collect_messages already registered for DAG: dump_to_s3
[2022-10-05T09:27:25.841+0000] {taskmixin.py:205} WARNING - Dependency <Task(_PythonDecoratedOperator): collect_messages>, dump_to_s3 already registered for DAG: dump_to_s3
[2022-10-05T09:27:25.841+0000] {taskmixin.py:205} WARNING - Dependency <Task(_PythonDecoratedOperator): dump_to_s3>, collect_messages already registered for DAG: dump_to_s3
[2022-10-05T09:27:25.841+0000] {taskmixin.py:205} WARNING - Dependency <Task(_PythonDecoratedOperator): collect_messages>, dump_to_s3 already registered for DAG: dump_to_s3
[2022-10-05T09:27:25.841+0000] {taskmixin.py:205} WARNING - Dependency <Task(_PythonDecoratedOperator): dump_to_s3>, collect_messages already registered for DAG: dump_to_s3
[2022-10-05T09:27:25.841+0000] {taskmixin.py:205} WARNING - Dependency <Task(_PythonDecoratedOperator): collect_messages>, dump_to_s3 already registered for DAG: dump_to_s3
[2022-10-05T09:27:25.841+0000] {taskmixin.py:205} WARNING - Dependency <Task(_PythonDecoratedOperator): dump_to_s3>, collect_messages already registered for DAG: dump_to_s3
[2022-10-05T09:27:25.841+0000] {taskmixin.py:205} WARNING - Dependency <Task(_PythonDecoratedOperator): collect_messages>, dump_to_s3 already registered for DAG: dump_to_s3
[2022-10-05T09:27:25.841+0000] {taskmixin.py:205} WARNING - Dependency <Task(_PythonDecoratedOperator): dump_to_s3>, collect_messages already registered for DAG: dump_to_s3
[2022-10-05T09:27:25.841+0000] {taskmixin.py:205} WARNING - Dependency <Task(_PythonDecoratedOperator): collect_messages>, dump_to_s3 already registered for DAG: dump_to_s3
[2022-10-05T09:27:25.841+0000] {taskmixin.py:205} WARNING - Dependency <Task(_PythonDecoratedOperator): dump_to_s3>, collect_messages already registered for DAG: dump_to_s3
[2022-10-05T09:27:25.978+0000] {task_command.py:384} INFO - Running <TaskInstance: dump_to_s3.collect_messages manual__2022-10-05T09:27:21.016272+00:00 [running]> on host b44ee3804a1a
[2022-10-05T09:27:26.075+0000] {taskinstance.py:1590} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dump_to_s3
AIRFLOW_CTX_TASK_ID=collect_messages
AIRFLOW_CTX_EXECUTION_DATE=2022-10-05T09:27:21.016272+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-10-05T09:27:21.016272+00:00
[2022-10-05T09:27:26.087+0000] {logging_mixin.py:117} INFO - DATA:
[2022-10-05T09:27:26.087+0000] {logging_mixin.py:117} INFO - {"courseOverGround":299.2,"latitude":59.154498,"longitude":5.557565,"name":"MASTRAFJORD","rateOfTurn":0,"shipType":60,"speedOverGround":13,"trueHeading":293,"mmsi":259216000,"msgtime":"2022-10-05T09:23:27+00:00"}
[2022-10-05T09:27:26.094+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/airflow/decorators/base.py", line 188, in execute
    return_value = super().execute(context)
  File "/usr/local/lib/python3.10/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.10/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/workspaces/pipeline-environment/test_airflow/dags/pipeline.py", line 54, in collect_messages
    asyncio.run(get_messages(start_time, end_time))
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/workspaces/pipeline-environment/test_airflow/dags/pipeline.py", line 82, in get_messages
    while start_time < end_time:
TypeError: '<' not supported between instances of 'datetime.datetime' and 'str'
[2022-10-05T09:27:26.097+0000] {taskinstance.py:1401} INFO - Marking task as FAILED. dag_id=dump_to_s3, task_id=collect_messages, execution_date=20221005T092721, start_date=20221005T092725, end_date=20221005T092726
[2022-10-05T09:27:26.136+0000] {standard_task_runner.py:102} ERROR - Failed to execute job 46 for task collect_messages ('<' not supported between instances of 'datetime.datetime' and 'str'; 10799)
[2022-10-05T09:27:26.162+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-10-05T09:27:26.208+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
