[2022-10-23T21:31:27.504+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: slack_notify.dummy manual__2022-10-23T21:31:23.471211+00:00 [queued]>
[2022-10-23T21:31:27.509+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: slack_notify.dummy manual__2022-10-23T21:31:23.471211+00:00 [queued]>
[2022-10-23T21:31:27.509+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-10-23T21:31:27.509+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-10-23T21:31:27.509+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-10-23T21:31:27.541+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): dummy> on 2022-10-23 21:31:23.471211+00:00
[2022-10-23T21:31:27.543+0000] {standard_task_runner.py:54} INFO - Started process 17167 to run task
[2022-10-23T21:31:27.546+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'slack_notify', 'dummy', 'manual__2022-10-23T21:31:23.471211+00:00', '--job-id', '129', '--raw', '--subdir', 'DAGS_FOLDER/slack_test.py', '--cfg-path', '/tmp/tmp9jlkgnb0']
[2022-10-23T21:31:27.547+0000] {standard_task_runner.py:83} INFO - Job 129: Subtask dummy
[2022-10-23T21:31:27.548+0000] {dagbag.py:525} INFO - Filling up the DagBag from /workspaces/pipeline-environment/airflow_ais/dags/slack_test.py
[2022-10-23T21:31:27.646+0000] {task_command.py:384} INFO - Running <TaskInstance: slack_notify.dummy manual__2022-10-23T21:31:23.471211+00:00 [running]> on host 5565aed88557
[2022-10-23T21:31:27.729+0000] {taskinstance.py:1590} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=slack_notify
AIRFLOW_CTX_TASK_ID=dummy
AIRFLOW_CTX_EXECUTION_DATE=2022-10-23T21:31:23.471211+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-10-23T21:31:23.471211+00:00
[2022-10-23T21:31:27.730+0000] {logging_mixin.py:117} INFO - ---------------------
[2022-10-23T21:31:27.730+0000] {logging_mixin.py:117} INFO - THIS IS A SLACK MESSAGE DAG
[2022-10-23T21:31:27.730+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.10/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/workspaces/pipeline-environment/airflow_ais/dags/slack_test.py", line 22, in my_fun
    raise Exception('I know Python!')
Exception: I know Python!
[2022-10-23T21:31:27.732+0000] {taskinstance.py:1401} INFO - Marking task as FAILED. dag_id=slack_notify, task_id=dummy, execution_date=20221023T213123, start_date=20221023T213127, end_date=20221023T213127
[2022-10-23T21:31:27.736+0000] {logging_mixin.py:117} WARNING - /usr/local/lib/python3.10/site-packages/airflow/utils/context.py:204 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-10-23T21:31:27.737+0000] {logging_mixin.py:117} WARNING - /home/vscode/.local/lib/python3.10/site-packages/airflow/providers/slack/operators/slack_webhook.py:162 UserWarning: Found unexpected keyword-argument(s) 'link_names' in `send` method. This argument(s) have no effect.
[2022-10-23T21:31:27.740+0000] {base.py:71} INFO - Using connection ID 'slack_webhook' for task execution.
[2022-10-23T21:31:28.383+0000] {standard_task_runner.py:102} ERROR - Failed to execute job 129 for task dummy (I know Python!; 17167)
[2022-10-23T21:31:28.399+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-10-23T21:31:28.441+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
